// Auto-generated by tools/extract_norm_stats from results/norm_stats.json.
// DO NOT EDIT. Re-run extract_norm_stats to regenerate.
//
// Precision rationale (see results/known_limitations.md): CGM stats emit at
// %.4f and IOB/COB at %.7f to preserve the currently-shipped float32 bit
// patterns. Emitting at higher precision would alter the CGM constants by
// ~2.6 ULP and break bit-identity with the in-tree weights blob.

#pragma once

namespace osdn_weights {

static constexpr float MEAN_MG_DL = 157.6580f;
static constexpr float STD_MG_DL  =   60.4485f;

static constexpr float IOB_MEAN   = 0.6985540f;
static constexpr float IOB_STD    = 0.8231367f;
static constexpr float COB_MEAN   = 0.2245205f;
static constexpr float COB_STD    = 0.4076972f;

}  // namespace osdn_weights
