#pragma once
#include <cstdint>
#include <cstddef>

// Six normalization constants (MEAN_MG_DL, STD_MG_DL, IOB_MEAN/STD,
// COB_MEAN/STD) live in osdn_norm_stats.gen.h — generated by
// tools/extract_norm_stats from results/norm_stats.json so they cannot
// drift from the trainer's normalize_inplace output. The gen file is
// the single source-of-truth; do not redefine them here.
#include "osdn_norm_stats.gen.h"

namespace osdn_weights {

// LOOKBACK pinned to the trainer's --lookback for the brain-mode run.
// Stays here (not generated) because the firmware uses it as an array
// dimension at compile time and the value is hand-pinned to the shipped
// blob, not derived from training data.
static constexpr int LOOKBACK = 144;

// Runtime shape constants emitted by blob_to_header from the blob's
// 32-byte osdn_blob header. Firmware uses these (not compile-time
// duplicates) so the constants and the blob can't disagree silently.
extern const std::uint32_t BLOB_H;
extern const std::uint32_t BLOB_K;
extern const std::uint32_t BLOB_D_IN;
extern const std::uint32_t BLOB_N_LAYERS;
extern const std::size_t   BLOB_LEN;
extern const float         BLOB[];

}
