#include "osdn_blob.hpp"
#include <cstdio>
#include <string>
#include <fstream>
#include <vector>
#include <iomanip>

int main(int argc, char** argv) {
    std::string in_path, out_path;
    for (int i = 1; i < argc; ++i) {
        std::string k = argv[i];
        auto next = [&]() -> std::string { return (i + 1 < argc) ? argv[++i] : ""; };
        if      (k == "--in")  in_path  = next();
        else if (k == "--out") out_path = next();
        else {
            std::fprintf(stderr, "unknown arg: %s\n", k.c_str());
            return 2;
        }
    }
    if (in_path.empty() || out_path.empty()) {
        std::fprintf(stderr, "usage: blob_to_header --in weights.bin --out osdn_weights.cpp\n");
        return 2;
    }

    std::ifstream f(in_path, std::ios::binary);
    if (!f) { std::fprintf(stderr, "cannot open %s\n", in_path.c_str()); return 1; }

    osdn_blob::Header h{};
    std::string err;
    if (!osdn_blob::read_header(f, h, err)) {
        std::fprintf(stderr, "%s: header invalid: %s\n", in_path.c_str(), err.c_str());
        return 1;
    }

    f.seekg(0, std::ios::end);
    std::streamsize bytes = f.tellg();
    f.seekg(static_cast<std::streamoff>(osdn_blob::HEADER_BYTES), std::ios::beg);
    std::streamsize payload_bytes =
        bytes - static_cast<std::streamsize>(osdn_blob::HEADER_BYTES);
    if (payload_bytes <= 0 || (payload_bytes % 4) != 0) {
        std::fprintf(stderr, "%s: bad payload size %lld\n",
                     in_path.c_str(), static_cast<long long>(payload_bytes));
        return 1;
    }
    std::size_t n_floats = static_cast<std::size_t>(payload_bytes) / 4;
    if (n_floats != h.param_count) {
        std::fprintf(stderr,
                     "%s: header param_count %u disagrees with file payload %zu floats\n",
                     in_path.c_str(), h.param_count, n_floats);
        return 1;
    }
    std::vector<float> blob(n_floats);
    f.read(reinterpret_cast<char*>(blob.data()), payload_bytes);
    if (f.gcount() != payload_bytes) {
        std::fprintf(stderr, "%s: short read\n", in_path.c_str());
        return 1;
    }

    std::ofstream o(out_path);
    if (!o) { std::fprintf(stderr, "cannot write %s\n", out_path.c_str()); return 1; }

    o << "// Auto-generated by blob_to_header from " << in_path << "\n"
      << "// " << osdn_blob::format_header(h) << "\n"
      << "// DO NOT EDIT. Re-run blob_to_header to regenerate.\n\n"
      << "#include \"osdn_weights.h\"\n\n"
      << "namespace osdn_weights {\n\n"
      << "const std::uint32_t BLOB_H        = " << h.H        << ";\n"
      << "const std::uint32_t BLOB_K        = " << h.K        << ";\n"
      << "const std::uint32_t BLOB_D_IN     = " << h.D_in     << ";\n"
      << "const std::uint32_t BLOB_N_LAYERS = " << h.n_layers << ";\n"
      << "const std::size_t   BLOB_LEN      = " << n_floats   << ";\n\n"
      << "const float BLOB[" << n_floats << "] = {\n"
      << std::scientific << std::setprecision(9);
    for (std::size_t i = 0; i < n_floats; ++i) {
        if (i % 4 == 0) o << "    ";
        o << blob[i] << "f";
        if (i + 1 < n_floats) o << ",";
        if (i % 4 == 3 || i + 1 == n_floats) o << "\n";
        else o << " ";
    }
    o << "};\n\n"
      << "}  // namespace osdn_weights\n";

    std::fprintf(stderr,
                 "wrote %zu floats (%lld payload bytes, %zu header bytes) to %s\n",
                 n_floats, static_cast<long long>(payload_bytes),
                 osdn_blob::HEADER_BYTES, out_path.c_str());
    std::fprintf(stderr, "shape: %s\n", osdn_blob::format_header(h).c_str());
    return 0;
}
